### ISSUE TITLE
Treat Migration Guide: issue with importing images

### ISSUE THREAD

**Issue by danielberndt** [seek-oss/vanilla-extract#22]
I just went ahead to migrate our 61 `.treat.js` files in our project to vanilla-extract and it all went really smoothly. Good job for making the migration so painless!
Of course we're using none of the css variables feature yet, but the nice thing is that we can now progressively migrate it piece by piece

One thing that broke was this though:

```js
import stepBgImg from "./imgs/steps-bg.svg";
const container = style({
  backgroundImage: `url("${stepBgImg}")`
})
```

it showed a rather long and unreadable error message before realising that vanilla-extract is probably more clever than I've expected. So I tried doing

```js
const container = style({
  backgroundImage: `url('./imgs/steps-bg.svg')`,
})
```

which worked!

So maybe this is worth mentioning in the migration guide?

Cheers!

**Comment by markdalgleish** [comment]
Ah yeah, this is a good catch!

You should be able to get the old behaviour back (I prefer it personally) by setting css-loader's [`url`](https://webpack.js.org/loaders/css-loader/#url) option to `false` for CSS files generated by vanilla-extract. You can target/exclude these files because they are named `*.vanilla.css`.

For example, here's how you'd use default settings for normal CSS files, but customise the settings for vanilla-extract. (Note, I haven't tested this myself, let me know if I got anything wrong)

```js
module.exports = {
  module: {
    rules: [
      {
        test: (file) => file.endsWith(".vanilla.css"),
        use: [
          MiniCssExtractPlugin.loader,
          {
            loader: "css-loader",
            options: {
              url: false
            }
          },
        ],
      },
      {
        test: (file) => file.endsWith(".css") && !file.endsWith(".vanilla.css"),
        use: [
          MiniCssExtractPlugin.loader,
          "css-loader"
        ],
      },
    ],
  },
  plugins: [
    new VanillaExtractPlugin()
  ]
};

```

The reason there's a difference here is that the vanilla-extract webpack plugin no longer handles the generated CSS file for you. Instead, we expect you to be handling regular CSS files already, but that means you're now inheriting default URL handling, which IMO doesn't feel as right with CSS-in-JS and can actually lead to weird bugs if you're passing file paths around between files.

It would definitely be a good idea to add something about this to the migration guide.

**Comment by danielberndt** [comment]
Thanks for the explanation, makes perfect sense 👍 

As my setup is based on `create-react-app`, I guess I'm fine with the default `css-loader` behaviour to keep my overwrites as light as possible.

Just for reference here's my current `config-overrides.js` to use `create-react-app` via `react-app-rewired@2.1.7`

```js
const {VanillaExtractPlugin} = require("@vanilla-extract/webpack-plugin");
const {getBabelLoader} = require("customize-cra");

module.exports = function override(config) {
  const loader = getBabelLoader(config);
  loader.options.plugins.push("@vanilla-extract/babel-plugin");
  config.plugins.push(new VanillaExtractPlugin());
  return config;
};
```

**Comment by markdalgleish** [comment]
Updated the [treat migration guide](https://github.com/seek-oss/vanilla-extract/blob/master/docs/treat-migration-guide.md#url-handling-should-be-disabled-for-vanillacss-files). Thanks for raising this!
