### ISSUE TITLE
Potential Memory Leak / Dev Performance when Used with Treat ?

### ISSUE THREAD

**Issue by phil-lgr** [seek-oss/vanilla-extract#231]
### Describe the bug

While developing code with treat and vanilla, I experience big problem with RAM usage

After saving .treat.ts or .css.ts files repeatedly, the node process leak memory and grow to all heap size available causing a crash.

For example, see the ram usage of the node process a couple of saves:

![image](https://user-images.githubusercontent.com/9644867/125717226-7d4aaa1d-b2d3-4361-bc97-0e6ea97e6bf2.png)

And after 10 more saves:

![image](https://user-images.githubusercontent.com/9644867/125717912-f8e10889-700a-4ab7-9877-d257ade925b6.png)

The first node process goes from 296MB to 400MB with 0 code change... just pressing enter and saving (triggering new build check)

### Link to reproduction

https://github.com/newrade/vanilla-treat-repro

### System Info

Output of `npx envinfo --system --npmPackages @vanilla-extract/css,@vanilla-extract/webpack-plugin,@vanilla-extract/esbuild-plugin,@vanilla-extract/vite-plugin,@vanilla-extract/sprinkles,webpack,esbuild,vite --binaries --browsers`:

```node
System:
    OS: macOS 11.4
    CPU: (8) arm64 Apple M1
    Memory: 76.94 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 16.5.0 - ~/.nvm/versions/node/v16.5.0/bin/node
    Yarn: 1.22.10 - /opt/homebrew/bin/yarn
    npm: 7.19.1 - ~/.nvm/versions/node/v16.5.0/bin/npm
  Browsers:
    Brave Browser: 91.1.25.68
    Chrome: 91.0.4472.114
    Safari: 14.1.1
  npmPackages:
    @vanilla-extract/css: ^1.1.0 => 1.1.0 
    webpack: ^5 => 5.44.0 
```

**Comment by phil-lgr** [comment]
I also see a problem with vanilla recompiling for a .treat code change

![image](https://user-images.githubusercontent.com/9644867/125718401-f507d59b-1243-43c6-a46a-8d5646df5023.png)

**Comment by phil-lgr** [comment]
After saving theme.css.ts about 20 times

![image](https://user-images.githubusercontent.com/9644867/125718584-1e7f682d-4c60-46cc-97ae-6b43f7cf95c6.png)

**Comment by mattcompiles** [comment]
Does this problem occur in a straight vanilla project?

**Comment by phil-lgr** [comment]
I can create a branch with no .treat code if you want, let me know if you want me to do it.

You can easily comment out the treat code in `gatsby-site/`

But I see no problem with actual setup and packages... everything is bare bone, yet I see the problem here as well

IMO Treat and vanilla should work together since many users are migrating to vanilla-extract

**Comment by phil-lgr** [comment]
I made a branch with no treat files being imported

https://github.com/newrade/vanilla-treat-repro/tree/vanilla-only

```
git clone git@github.com:newrade/vanilla-treat-repro.git
cd vanilla-treat-repro
git checkout vanilla-only
```

I don't see the RAM usage going up with no treat files involved

I guess it's a treat issue then

**Comment by phil-lgr** [comment]
I went my in my main repo with 120 + components 

and I changed all imports 

```
import { Details, Paragraph, Summary, useTreatTheme } from '@newrade/core-react-ui';
```
to
```
import { Details, Paragraph, Summary, useTreatTheme } from '@newrade/core-react-ui/src';
```

So it would not use the .js versions... and the problem seems to go away

I guess one of the plugin has a problem with importing files from /lib/ vs /src/ version of the same files?

Is there a way to tell both vanilla and treat to only consider .js files?

**Comment by phil-lgr** [comment]
I did another test in my repo (with .treat files) with /src/ import 

Saving a package.json 20 times

![image](https://user-images.githubusercontent.com/9644867/125805635-8c93a1fd-838f-4336-805b-ecfcafafba1a.png)

After some time the RAM usage go up dramatically (from 2GB to 3.4GB with no real code change)

I could not reproduce this with the vanilla only repro above

**Comment by phil-lgr** [comment]
The other thing I don't get is why saving a treat file or any file actually, triggers vanilla-extract as well?

If you go in the repro repo and save `packages/core-react-ui/package.json`

I get this

![image](https://user-images.githubusercontent.com/9644867/125807139-ce3f1823-683f-41bf-9c1e-44ee88a489b2.png)


It rebuilds everything even though there are no code change

**Comment by phil-lgr** [comment]
in `vanilla-extract-webpack-plugin.cjs.dev.js`

![image](https://user-images.githubusercontent.com/9644867/125809384-2936cef3-9c81-42df-a060-abdd6b7396b1.png)

this.cache does not seem to have an entry for any file, it just says `No cached compilation.` every time

**Comment by phil-lgr** [comment]
> I went my in my main repo with 120 + components
> 
> and I changed all imports
> 
> ```
> import { Details, Paragraph, Summary, useTreatTheme } from '@newrade/core-react-ui';
> ```
> 
> to
> 
> ```
> import { Details, Paragraph, Summary, useTreatTheme } from '@newrade/core-react-ui/src';
> ```
> 
> So it would not use the compiled (tsc) `.js` versions... and the problem seems to go away
> 
> I guess one of the plugin has a problem with importing files from `/lib/` vs `/src/` version of the same files?
> 
> Is there a way to tell both vanilla and treat to only consider `.js` files?
> 
> Or the inverse, to only consider `.tsx?` files?

Ok for this there is already support for a `test` option:

```js
module.exports = {
  plugins: [{
    resolve: 'gatsby-plugin-vanilla-extract', 
    options: {
      test: /\.css\.(js|jsx)$/
    }
  }],
};
```

**Comment by mattcompiles** [comment]
Ok there is a lot going on here. From what I can see there are a few distinct issues you're reporting. 
- A potential memory leak issue with treat (rather than vanilla-extract)
- Saves to unrelated files cause `.css.ts` files to be loaded unnecessarily (also happens in treat)
  - This seem like a webpack issue as webpack controls what loaders run, not vanilla-extract
- Having `.css.js` and `.css.ts` versions of the same file causes both to be loaded.
  - I am the least clear on this one, but once again this doesn't really have anything to do with vanilla-extract, webpack chooses what files are needed to be loaded and we just load what is passes us. The `test` option gives you all the control we have. 

Correct me if I'm wrong, but unless I'm missing something I don't see any vanilla-extract issues here.

**Comment by phil-lgr** [comment]
> A potential memory leak issue with treat (rather than vanilla-extract)

Do you want me to open the issue on the treat repo? My general feeling is that Treat won't be supported for long, as vanilla-extract is the successor.

> Saves to unrelated files cause .css.ts files to be loaded unnecessarily (also happens in treat)
This seems like a webpack issue as webpack controls what loaders run, not vanilla-extract

My concern for this one is that it seems that no cache is found when reloading files after NO code change, it doesn't look normal to see `No cached compilation` when no code has changed. Are you actually seeing the cached being used when you enable `DEBUG=vanilla-extract*` I don't think I have seen `Using cached compilation...` once.

>  Having .css.js and .css.ts versions of the same file causes both to be loaded.
I am the least clear on this one, but once again this doesn't really have anything to do with vanilla-extract, webpack chooses what files are needed to be loaded, and we just load what is passes us. The test option gives you all the control we have.

So, I guess... I could set up 2 vanilla plugins? One for css.js files, one for css.ts files? I think consuming mixed .js .ts files in a vanilla project is going to be fairly common. At seek, you don't have this scenario? How do you consume components that use vanilla-extract?

**Comment by mattcompiles** [comment]
**Regarding the `No cached compilation` message**

This message is nothing to be concerned about. In an older version, the webpack child compilation process used more sub-compilations and cached them. That was removed as there were some issues as a result. The cache code didn't get removed (but probably should be) and as such never gets a cache hit. The cache is wiped at the start of each watch mode run of webpack so there shouldn't be a memory leak. 

However, this should not be confused with webpack 5's built in cache. They are completely unrelated.

**Regarding Monorepo compilation**

There's nothing wrong with targeting JS and TS files in the same project/plugin. Having a deeper look at your reproduction repo I can see what's happening. Each time the `tsc` build runs it rewrites the entire lib directory, even though only a single file has likely changed. This causes webpack to discard the build cache for **every file in the package**, rather than just the changed ones. If you modify a file in the lib directory directly you'll see that only that file is recompiled, as expected. 

What I would suggest is not using `tsc` as part of your local development and instead compiling the source files within in each package as part of your webpack build. There are a few ways to approach this but I'll plug the brilliant [preconstruct](https://preconstruct.tools/) as my suggestion. We use it internally to compile vanilla-extract and handle this stuff for us. The feature that's specifically relevant here is the [preconstruct dev command](https://preconstruct.tools/guides/using-preconstruct-dev-in-a-monorepo).

**Comment by phil-lgr** [comment]
> Each time the tsc build runs it rewrites the entire lib directory, even though only a single file has likely changed. 

I'm really surprised about that since I use `tsc --build` with `composite` enabled

Closing since the main issue with treat should be opened in the other repo

Thanks @mattcompiles !

**Comment by phil-lgr** [comment]
For those finding this issue, I was able to fix this problem by using `ts-loader`:

```ts
// in on-create-webpack-config export
/**
   * Add tsx support with ts-loader
   */
  if (config.module?.rules) {
    (config.module.rules as RuleSetRule[]) = [
      ...(config.module.rules as RuleSetRule[]).filter(negateTsLoaderPredicate),
      {
        ...getTypescriptBabelReactLoader({
          isDevelopment: isDevelopStage,
          tsLoaderOptions: {
            projectReferences: true,
            transpileOnly: true,
            logLevel: 'WARN',
          },
        }),
        exclude: /public|static|node_modules|treat\.ts/,
      },
    ] as RuleSetRule[];

    config.plugins?.push(getForkTsCheckerWebpackPlugin());
  }

  config.resolve = {
    ...config.resolve,
    plugins: [
      ...(config.resolve?.plugins || []),
      new TsconfigPathsPlugin({
        configFile: 'tsconfig.json',
        logLevel: 'WARN',
      }),
    ],
  };
```

The idea is that `ts-loader` is used with project references to build other packages, so webpack will know what to rebuild based on that. Notice also the `.treat.ts` files are excluded because they are handled by gatsby own rules... and also, the treat-plugin already applies HMR
