### ISSUE TITLE
Nextjs + vanilla-extract works inconsistently

### ISSUE THREAD

**Issue by daryawood** [seek-oss/vanilla-extract#396]
Hi team, we've stumbled across a very strange bug: build command won't work in some cases. We've created a minimal reproduction repo, where you can test it. Our most ambiguous finding — if you move styles somehow in a folder structure, it starts working. We don't want to blindly manipulate file structure as we couldn't find the source of the problem. Sometimes paths like `../../../../../../node_modules/virtual-resource-loader/` webpack handles correctly, sometimes — not. Hope you can shed some light on the issue.

Build command fails with the next message:
```
> Build error occurred
Error: Cannot find module '@roadtravel/client-react/styles/vars.css.ts.vanilla.css!=!../../../../../../node_modules/virtual-resource-loader/dist/virtual-resource-loader.cjs.js?{"source":"Ll8xcThwMWhtMCB7CiAgcGFkZGluZy1sZWZ0OiAyMHB4OwogIHBhZGRpbmctcmlnaHQ6IDIwcHg7Cn0="}!../../../../../../node_modules/@vanilla-extract/webpack-plugin/extracted/dist/vanilla-extract-webpack-plugin-extracted.cjs.js'
```

### Link to reproduction
https://github.com/daryawood/vanilla-extract-bug

### System Info

Output of `npx envinfo --system --npmPackages @vanilla-extract/css,@vanilla-extract/webpack-plugin,@vanilla-extract/esbuild-plugin,@vanilla-extract/vite-plugin,@vanilla-extract/sprinkles,webpack,esbuild,vite --binaries --browsers`:

```node
  System:
    OS: macOS 11.5.1
    CPU: (8) x64 Apple M1
    Memory: 34.78 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.5 - /usr/local/bin/node
    Yarn: 3.0.2 - ~/Documents/vanilla-extract-bug/node_modules/.bin/yarn
    npm: 6.14.14 - /usr/local/bin/npm
  Browsers:
    Chrome: 94.0.4606.61
    Edge: 93.0.961.47
    Firefox: 92.0
    Safari: 14.1.2
```

**Comment by thekip** [comment]
I will also add a bit of my findings. 

Sometimes (we didn't understand why) webpack plugin generates path to `/virtual-resource-loader` with more '../' segments than it should. It goes out from project folder and webpack treat this module as external an instead of inlining resource it just left `require("@roadtravel/client-react/styles/vars.css.ts.vanilla.css!=!../../../../../../node_modules/virtual-resource-loader/dist/virtual-resource-loader.cjs.js?` which obviously doesn't work.

This happens only for imports in styles. Mean component.tsx > component.css.ts -> vars.css.ts (happens for this import) 

I also dug into the source code and tried to debug it, and found that for such files (imports inside css) vanilla-extract-webpack-plugin-loader.cjs.prod.js  calls to loaderUtils.stringifyRequest() with context of current file which is pointing to current procesed file directory instead of import file directory

in repo example: 

Given project structure: 
```
node_modules
projects/client-react/components/
projects/client-react/styles/
```

Where file
`projects/client-react/components/layout/cookie-bar/lib/cookie-bar.css.ts`

Imports 
`projects/client-react/styles/vars.css.ts`

and virtual-resource-loader resolved relatively to `cookie-bar.css.ts` instead of `vars.css.ts`
Which lead to 
`@roadtravel/client-react/styles/vars.css.ts.vanilla.css!=!../../../../../../node_modules/virtual-resource-loader/dist/virtual-resource-loader.cjs.js?`

Instead of
`@roadtravel/client-react/styles/vars.css.ts.vanilla.css!=!../../../node_modules/virtual-resource-loader/dist/virtual-resource-loader.cjs.js?`

The strange thing is that in some other cases where i debugged the same construction was succefuly parsed by webpack and worked with no issue. 

Tip: 
You can easily spot an issue by opening `projects/client-react/.next/server/pages/_app.js` after build (even after failed build) and checking it content. This is an artefact created by webpack where you can check what was actually generated.

**Comment by thekip** [comment]
Well, we've fixed the issue. The solution is quite simple, just switch to Emotion.
