### ISSUE TITLE
CRA- Craco: Styles were unable to be assigned to a file

### ISSUE THREAD

**Issue by 2manoj1** [seek-oss/vanilla-extract#410]
### Describe the bug

Getting "Styles were unable to be assigned to a file" error in CRA with craco setup

### Link to reproduction

https://codesandbox.io/s/craco-vanilla-extract-boiler-plate-forked-b1ygs?file=/src/App.tsx

### System Info
Codesanbox - chrome brwoser
<img width="1440" alt="Screenshot 2021-10-11 at 9 34 41 AM" src="https://user-images.githubusercontent.com/15128569/136731699-baa47541-14db-4678-b163-e7aebe96a5b5.png">

**Comment by hwhmeikle** [comment]
Also getting this issue. I definitely understand this is probably not helped by the fact we're having to override CRA's webpack config - but is there anything glaringly obvious that might be causing this?

**Comment by mattcompiles** [comment]
I just pulled this sandbox down locally and I couldn't start it due to some other strange errors that seemed to be related to clashing versions of mini-css-extract-plugin. After removing the deps for css-loader and mini-css-extract-plugin I could start the app just fine. 

I'd suggest making sure your css-loader and mini-css-extract-plugin versions are in sync with react-scripts.
