### ISSUE TITLE
`@vanilla-extract/vite-plugin@^3` + `vite-tsconfig-paths` = Unable to locate /abc/def/vanillaStyles.css.ts$$$xxx in the CSS map.

### ISSUE THREAD

**Issue by kompot** [seek-oss/vanilla-extract#427]
### Describe the bug
`@vanilla-extract/vite-plugin` @ `v3.0.0` broke compatibility with `vite-tsconfig-paths`. After upgrading to `^3` the following is seen in the console when trying to combine with `vite-tsconfig-paths`

`[vite] Internal server error: Unable to locate /src/default/vanillaStyles.css.ts$$$xxx in the CSS map.`

Downgrading to ^2 fixes the problem.

### Link to reproduction

https://github.com/kompot/vite-vanilla-extract-tsconfig-paths-bug

### System Info

```node
  System:
    OS: macOS 11.5.2
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 135.09 MB / 16.00 GB
    Shell: 3.3.1 - /usr/local/bin/fish
  Binaries:
    Node: 16.10.0 - /usr/local/bin/node
    Yarn: 1.22.15 - /usr/local/bin/yarn
    npm: 7.24.0 - /usr/local/bin/npm
  Browsers:
    Brave Browser: 89.1.21.77
    Chrome: 95.0.4638.54
    Edge: 94.0.992.47
    Firefox: 68.0.2
    Firefox Developer Edition: 94.0
    Safari: 14.1.2
    Safari Technology Preview: 15.0
  npmPackages:
    @vanilla-extract/css: ^1 => 1.6.2
    @vanilla-extract/vite-plugin: ^3 => 3.0.0
    @vanilla-extract/webpack-plugin: ^2 => 2.1.0
    vite: ^2.6 => 2.6.10
```

**Comment by Katarina-UBCO** [comment]
This happens to me, too. I assume, the problem is that `/../some-path` gets overridden to `/some-path` by `vite:import-analysis`. As a result, `cssMap` stores the source under the different key.

This is where the source is stored under `/../some-path`:
https://github.com/seek-oss/vanilla-extract/blob/076b02d91f22d0b61df2dd9edd875f86ac4a55ea/packages/vite-plugin/src/index.ts#L152

This is where the we are trying to retrieve the source by wrong key (`/some-path`):
https://github.com/seek-oss/vanilla-extract/blob/076b02d91f22d0b61df2dd9edd875f86ac4a55ea/packages/vite-plugin/src/index.ts#L69

A possible fix could be to use absolute paths as keys?

**Comment by Katarina-UBCO** [comment]
I've created a pull request with the fix https://github.com/seek-oss/vanilla-extract/pull/457
