### ISSUE TITLE
url( ) local imports does not works with esbuild and esbuild-plugin plugin

### ISSUE THREAD

**Issue by dmytro-shpak** [seek-oss/vanilla-extract#462]
### Describe the bug
Can not setup local url( ) import in css.ts files

### Link to reproduction
https://github.com/dmytro-shpak/esbuild-vanilla-extract-bug/
```
npm install
npm test
```

> Could not resolve "./x.svg" (the plugin "vanilla-extract" didn't set a resolve directory)`
### System Info

Output of `npx envinfo --system --npmPackages @vanilla-extract/css,@vanilla-extract/webpack-plugin,@vanilla-extract/esbuild-plugin,@vanilla-extract/vite-plugin,@vanilla-extract/sprinkles,webpack,esbuild,vite --binaries --browsers`:

```node
  System:
    OS: Linux 5.4 Ubuntu 20.04.3 LTS (Focal Fossa)
    CPU: (16) x64 AMD Ryzen 7 3700X 8-Core Processor
    Memory: 58.36 GB / 62.74 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
    npm: 8.1.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
  npmPackages:
    @vanilla-extract/css: ^1.6.3 => 1.6.3 
    @vanilla-extract/esbuild-plugin: ^2.0.0 => 2.0.0 
    esbuild: ^0.13.13 => 0.13.13 
```

### The workaround

Use babel for *.css.ts files
```
import babel from 'esbuild-plugin-babel';
```
```
        plugins: [
            babel({
                filter: /.*.css.ts/,
                config: {
                    presets: ['@babel/preset-typescript'],
                    plugins: ['@vanilla-extract/babel-plugin'],
                },
            }),
        ],
```

**Comment by mattcompiles** [comment]
Thanks for raising this. There might be some esbuild limitations we need to combat here as I'm not sure we can allow asset imports within the child compilation process due to using the `write: false` setting. Will report back here once we've worked out the right path forward.

**Comment by dmytro-shpak** [comment]
there is similar issue in other esbuild plugin (https://github.com/EMH333/esbuild-svelte/issues/69). I have try to send
```
resolveDir: dirname(path) 
```
in **onLoad** callback result, but the issue was not resolved

**Comment by mattcompiles** [comment]
You're on the right track but the path isn't valid because it's a virtual module that doesn't exist in the filesystem. I need to do some refactoring to get this fixed but I hope to get it fixed soon.

**Comment by dmytro-shpak** [comment]
I giving up.

**Comment by ig2r** [comment]
We're affected by this issue as well, trying to load a bundled font via `fontFace` in a component library. Unwilling to bring in Babel and switch to "runtime" construction of styles, we have the following workaround in place for now:

- Plain old "fonts.css" with a `@font-face` statement that loads the required font(s):

      @font-face {
        font-family: "SomeBrand Sans";
        src: url("../assets/fonts/SomeBrandSans-Light.woff2") format("woff2");
        font-weight: 300;
        font-style: normal;
      }
      ...

  (Ensure there's an ESBuild loader for `.woff2` files obviously.)

- Reference that `font-family` name in a Sprinkles property to get a symbolic name to work with:

      const fontProperties = defineProperties({
        properties: {
          fontFamily: {
            'somebrand-sans': 'SomeBrand Sans',
          },
      ...

- Import "fonts.css" from the library's "index.ts" so that ESBuild will merge it into the CSS bundle along with the generated styles.

Maybe that's helpful for someone else stumbling into this issue until `url()` resolution works as expected.

Apart from that, our experience with vanilla-extract so far has been awesome!

**Comment by mfunkie** [comment]
I attempted to get around this with a `postcss-url` plugin, in which I copy my .png or .svg background `url()` to the assets directory in output and rewrite the URL, but it really only works for DEV mode and doesn't respect vite output directories.  Using babel to process didn't really flow well with my codebase, so I'm kinda stumped here.
