### ISSUE TITLE
Result of recipe function is a string in test environment - jest

### ISSUE THREAD

**Issue by Attimo91** [seek-oss/vanilla-extract#687]
result of recipe function is a string in unit tests(jest) - it works fine(is a function) in the app. I have added babel plugin according to the documentation https://vanilla-extract.style/documentation/setup/#test-environments.

`const button = recipe({
  base,
  variants: {
    variant: variants,
    size: sizes,
  },
});`

`className={button({ variant, size })}` <= I am getting error here: `Error: Uncaught [TypeError: (0 , _Button.button) is not a function]`

**Comment by rafal2228** [comment]
I'm also facing the same issue when trying to import `.css.ts` files within jest environment. What I found is that they are getting correctly processed by babel plugin when I change the import from:

```
import { recipe } from 'styles.css'
```

to

```
import { recipe } from 'styles.css.ts'
```

Any ideas why this might be happening? @mattcompiles

**Comment by mattcompiles** [comment]
This issue often occurs when your test environment is configured to return an [identity-obj-proxy](https://www.npmjs.com/package/identity-obj-proxy) when it is sees a `.css` extension. This was a common pattern in projects using CSS modules, often seen in jest setups. The issue is that jest doesn't resolve the final file path of the file, it only looks at the request in the consuming file, so it's impossible to tell the difference between a `.css.ts` file and a CSS module. 

Ideally remove the config doing this, however if you need to support both in the same project then I'd move to using the `.module.css` extension. This will allow you handle those files differently in your jest transform rules.  

If this isn't the issue let me know.

**Comment by rafal2228** [comment]
This was exactly the issue :) Turns out NX is by default returning [identity-obj-proxy](https://www.npmjs.com/package/identity-obj-proxy) as you have mentioned:

https://github.com/nrwl/nx/blob/0c8eade82e4c3a4d555f7407c0a324d982bcbd59/packages/jest/plugins/resolver.ts#L43-L51

Thanks a lot :)
