### ISSUE TITLE
HMR does not work with @vanilla-extract/vite-plugin": "^3.2.1 but works in 2.1.3.

### ISSUE THREAD

**Issue by cpakken** [seek-oss/vanilla-extract#735]
### Describe the bug

Referenced issued: https://github.com/seek-oss/vanilla-extract/issues/578 (Closed but bug still exist)

I'm running "@vanilla-extract/vite-plugin": "^3.2.1" and HMR doesn't seem to be working. Tried switching to version 2.1.3 and HMR works fine.

Basic setup

- vite react template using pnpm create vite (react-ts option).
- Substituted .App-header with a vanilla-extract version.
- switch backgroundColor
- save
- See full reload on 3.2.1, and HMR on 2.1.3

Link to repo
https://github.com/cpakken/vite-vanilla-extract-test-hmr-not-working

### Reproduction

https://github.com/cpakken/vite-vanilla-extract-test-hmr-not-working

### System Info

```shell
windows 10
```

### Used Package Manager

pnpm

### Validations

- [x] Check that there isn't [already an issue](https://github.com/seek-oss/vanilla-extract/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by wobsoriano** [comment]
Can confirm this

**Comment by frandiox** [comment]
I noticed this as well. The WS message for HMR often works but the file downloaded by the browser is not updated, so refreshing the browser goes back to the previous state.
I think the reason is that the plugin is not adding the `?t=` query string to the file in order to bypass cache.
It should be fixed in https://github.com/seek-oss/vanilla-extract/pull/751
